react-dom.development.js:29895 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
AuthContext.jsx:90 WebSocket conectado.
AuthContext.jsx:91 WebSocket desconectado.
AuthContext.jsx:90 WebSocket conectado.
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294671995-t24bbbp3e
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672000-m97oosgkp
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672005-ldu0ufdph
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672006-byt36tfr6
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672009-1z963v9qq
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672011-bcukmvymm
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672014-np9x8znca
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672017-oa7hx637k
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672032-hxkyd1gy4
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672034-dxd7llj6o
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672038-dyhm7atyo
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672040-765cdrrbf
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672043-d5ka13gr4
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672045-y6drt2dog
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672048-o7hzp4n97
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672050-xxjbagwnh
react-dom.development.js:13123  Uncaught Error: Objects are not valid as a React child (found: object with keys {type, model}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13123:9)
    at reconcileChildFibers2 (react-dom.development.js:14064:7)
    at reconcileChildren (react-dom.development.js:19186:28)
    at updateHostComponent (react-dom.development.js:19953:3)
    at beginWork (react-dom.development.js:21657:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27490:7)
    at performUnitOfWork (react-dom.development.js:26596:12)
throwOnInvalidObjectType @ react-dom.development.js:13123
reconcileChildFibers2 @ react-dom.development.js:14064
reconcileChildren @ react-dom.development.js:19186
updateHostComponent @ react-dom.development.js:19953
beginWork @ react-dom.development.js:21657
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
react-dom.development.js:18704  The above error occurred in the <ErrorBoundary> component:

    at ErrorBoundary (http://localhost:5173/src/components/shared/ErrorBoundary.jsx?t=1759294114367:8:5)
    at App (http://localhost:5173/src/App.jsx?t=1759294469408:27:34)
    at AuthProvider (http://localhost:5173/src/context/AuthContext.jsx?t=1759293927111:29:32)
    at ToastProvider (http://localhost:5173/src/context/ToastContext.jsx:31:33)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18704
update.callback @ react-dom.development.js:18737
callCallback @ react-dom.development.js:15036
commitUpdateQueue @ react-dom.development.js:15057
commitLayoutEffectOnFiber @ react-dom.development.js:23430
commitLayoutMountEffects_complete @ react-dom.development.js:24727
commitLayoutEffects_begin @ react-dom.development.js:24713
commitLayoutEffects @ react-dom.development.js:24651
commitRootImpl @ react-dom.development.js:26862
commitRoot @ react-dom.development.js:26721
performSyncWorkOnRoot @ react-dom.development.js:26156
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
useErrorCapture.js:35 Error global capturado y reportado: global-js-1759294672058-oeaymopkw
react-dom.development.js:12056  Uncaught TypeError: Cannot read properties of null (reading 'componentStack')
    at ErrorBoundary.render (ErrorBoundary.jsx:89:63)
    at finishClassComponent (react-dom.development.js:19781:31)
    at updateClassComponent (react-dom.development.js:19727:24)
    at beginWork (react-dom.development.js:21650:16)
    at beginWork$1 (react-dom.development.js:27465:14)
    at performUnitOfWork (react-dom.development.js:26596:12)
    at workLoopSync (react-dom.development.js:26505:5)
    at renderRootSync (react-dom.development.js:26473:7)
    at recoverFromConcurrentError (react-dom.development.js:25889:20)
    at performSyncWorkOnRoot (react-dom.development.js:26135:20)
render @ ErrorBoundary.jsx:89
finishClassComponent @ react-dom.development.js:19781
updateClassComponent @ react-dom.development.js:19727
beginWork @ react-dom.development.js:21650
beginWork$1 @ react-dom.development.js:27465
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
AuthContext.jsx:91 WebSocket desconectado.
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
performSyncWorkOnRoot @ react-dom.development.js:26124
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27490
performUnitOfWork @ react-dom.development.js:26596
workLoopSync @ react-dom.development.js:26505
renderRootSync @ react-dom.development.js:26473
recoverFromConcurrentError @ react-dom.development.js:25889
performSyncWorkOnRoot @ react-dom.development.js:26135
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25690
errorsApi.js:14   POST http://127.0.0.1:8001/api/v1/errors/report 422 (Unprocessable Content)
reportError @ errorsApi.js:14
handleGlobalError @ useErrorCapture.js:31
errorsApi.js:28  Error al reportar error al backend: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
reportError @ errorsApi.js:28
await in reportError
handleGlobalError @ useErrorCapture.js:31
errorsApi.js:38 Error guardado localmente para reintento posterior
useErrorCapture.js:32  Error al reportar error global: Error: Error al reportar: 422 Unprocessable Content
    at reportError (errorsApi.js:23:19)
(anonymous) @ useErrorCapture.js:32
Promise.catch
handleGlobalError @ useErrorCapture.js:31
